/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasAtendidasRouteImport } from './routes/areas-atendidas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as LocacaoDeCacambaRouteImport } from './routes/locacao-de-cacamba'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as RetiradaDeEntulhoRouteImport } from './routes/retirada-de-entulho'
import { Route as SobreRouteImport } from './routes/sobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAtendidasRoute = AreasAtendidasRouteImport.update({
  id: '/areas-atendidas',
  path: '/areas-atendidas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const LocacaoDeCacambaRoute = LocacaoDeCacambaRouteImport.update({
  id: '/locacao-de-cacamba',
  path: '/locacao-de-cacamba',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const RetiradaDeEntulhoRoute = RetiradaDeEntulhoRouteImport.update({
  id: '/retirada-de-entulho',
  path: '/retirada-de-entulho',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/contato': typeof ContatoRoute
  '/locacao-de-cacamba': typeof LocacaoDeCacambaRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/retirada-de-entulho': typeof RetiradaDeEntulhoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/contato': typeof ContatoRoute
  '/locacao-de-cacamba': typeof LocacaoDeCacambaRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/retirada-de-entulho': typeof RetiradaDeEntulhoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/contato': typeof ContatoRoute
  '/locacao-de-cacamba': typeof LocacaoDeCacambaRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/retirada-de-entulho': typeof RetiradaDeEntulhoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas-atendidas'
    | '/contato'
    | '/locacao-de-cacamba'
    | '/perguntas-frequentes'
    | '/retirada-de-entulho'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areas-atendidas'
    | '/contato'
    | '/locacao-de-cacamba'
    | '/perguntas-frequentes'
    | '/retirada-de-entulho'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/areas-atendidas'
    | '/contato'
    | '/locacao-de-cacamba'
    | '/perguntas-frequentes'
    | '/retirada-de-entulho'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasAtendidasRoute: typeof AreasAtendidasRoute
  ContatoRoute: typeof ContatoRoute
  LocacaoDeCacambaRoute: typeof LocacaoDeCacambaRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  RetiradaDeEntulhoRoute: typeof RetiradaDeEntulhoRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-atendidas': {
      id: '/areas-atendidas'
      path: '/areas-atendidas'
      fullPath: '/areas-atendidas'
      preLoaderRoute: typeof AreasAtendidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacao-de-cacamba': {
      id: '/locacao-de-cacamba'
      path: '/locacao-de-cacamba'
      fullPath: '/locacao-de-cacamba'
      preLoaderRoute: typeof LocacaoDeCacambaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirada-de-entulho': {
      id: '/retirada-de-entulho'
      path: '/retirada-de-entulho'
      fullPath: '/retirada-de-entulho'
      preLoaderRoute: typeof RetiradaDeEntulhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasAtendidasRoute: AreasAtendidasRoute,
  ContatoRoute: ContatoRoute,
  LocacaoDeCacambaRoute: LocacaoDeCacambaRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  RetiradaDeEntulhoRoute: RetiradaDeEntulhoRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
